name: 构建Docker镜像并推送

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    # 当前脚本是在容器中运行的，对应的镜像是ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 源码
        uses: actions/checkout@v3

      
      - name: 打印 GitHub 上下文
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        # 将GITHUB的信息都打印出来，后面的脚本可以使用这些信息，例如后面的镜像TAG用的就是这里面的commit.id
        run: echo "Hello ${{ github.event.commits[0].id }}"

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          platforms: linux/amd64,linux/arm64

      - name: 登录 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 登录阿里云容器镜像服务
        run: |
          docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PASSWORD }} registry.cn-beijing.aliyuncs.com


      - name: 构建推送镜像
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/php82ext:${{ github.event.commits[0].message }}
            registry.cn-beijing.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACE }}/php82ext:${{ github.event.commits[0].message }}

